### ISSUE TITLE
Provide pure-floss build flavor

### ISSUE THREAD

**Issue by theScrabi** [tasomaniac/hackdash#1]
Hello,

I've tried to bring your app into f-droid. However it uses non-free libraries, therefore f-droid cant build. If you like this app to be part of f-droid please fix that issue.

https://gitlab.com/fdroid/fdroiddata/merge_requests/1428#note_12085585

Thanks.
rgds
Schabi

**Comment by tasomaniac** [comment]
Hey, thank you for the interest. I will try to create another buildFlavor to have an f-droid compatible version of the app. 
But I cannot do it soon. I already did the same for my other app [OpenLinkWith](https://github.com/tasomaniac/OpenLinkWith/). If you want to help, and do the same, I would appreciate it.

**Comment by tasomaniac** [comment]
Hey, it's been a long time but I finally did it just now. The app now has a special productFlavor called `floss`, it should now be fine to have it in f-droid.

**Comment by theScrabi** [comment]
Supper thanks,

but you also need to set an new version tag, in oder to let fdroid detect the changes.

**Comment by tasomaniac** [comment]
Tag 1.3 is added. Will soon be released to Play Store too. Cheers and thanks.
