### ISSUE TITLE
Consider migrating to http://spaceapi.fixme.ch/

### ISSUE THREAD

**Issue by ignisf** [tasomaniac/hackdash#2]
The spaceapi.net directory has been unmaintained for a while now unlike the fixme fork.

See https://spaceapi.fixme.ch/ & https://github.com/fixme-lausanne/OpenSpaceDirectory

**Comment by tasomaniac** [comment]
Thank you for the report. Really good to know that. 
How do you plan to maintain the fork? As far as I remember, there was an automated way to add your Hackerspace to the SpaceApi. Do you immediately get the newly added spaces?

I wonder if I should give option to users or should I just switch?

**Comment by ignisf** [comment]
The fork is not mine and AFAIK they just keep it simple -- modifications of the directory are done trough Github. I guess you could ask them. I just thought I should mention it.

**Comment by tasomaniac** [comment]
Thank you for bringing it up. Really good to know. I will check the differences. I will talk to the owners of the repo. :+1:

**Comment by tasomaniac** [comment]
The original SpaceAPI just returns an empty array currently. It's super bad. I'm migrating to `fixme` api.

**Comment by tasomaniac** [comment]
With the version 1.3, this will be included. Thanks for pointing me to the repo and the API.

**Comment by ignisf** [comment]
You are welcome :)
